.\" Copyright 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     cpioformat.5	5.3 (Berkeley) 5/10/91
.\"     @(#)cpio.4	5.3 (Berkeley) 5/10/91
.\"	changed to cpio.4 by JJ to match cpio(1) documentation
.\"
.TH CPIO 4 "May 10, 1991"
.SH NAME
\fBcpio\fR
\- format of cpio archive
.SH DESCRIPTION
The header structure,
when the
.BR \(mic
option of
\fBcpio\fR(1)
is not used, is:
.RS
.nf
struct {
	short	h_magic,
		h_dev;
	ushort	h_ino,
		h_mode,
		h_uid,
		h_gid;
	short	h_nlink,
		h_rdev,
		h_mtime[2],
		h_namesize,
		h_filesize[2];
	char	h_name[h_namesize rounded to word];
} Hdr;
.RE
.fi
.LP
When the
.BR \(mic
option is used,
the header information is described by:
.RS
.nf
sscanf(Chdr,"%6o%6o%6o%6o%6o%6o%6o%6o%11lo%6o%11lo%s",
&Hdr.h_magic, &Hdr.h_dev, &Hdr.h_ino, &Hdr.h_mode,
&Hdr.h_uid, &Hdr.h_gid, &Hdr.h_nlink, &Hdr.h_rdev,
&Longtime, &Hdr.h_namesize,&Longfile,Hdr.h_name);
.RE
.fi
.LP
.I "Longtime"
and
.I "Longfile"
are equivalent to
.I "Hdr.h_mtime"
and
.IR "Hdr.h_filesize" ,
respectively.
The contents of each file are recorded
in an element of the array
.IR archive ,
of varying length structures,
together with other items describing the file.
Every instance of
.I "h_magic"
contains the constant
070707 (octal).
The items
.I "h_dev"
through
.I "h_mtime"
have
meanings explained in
\fBstat\fR(2).
The length of the null-terminated path name
.IR "H_name" ,
including the null byte, is
given by
.IR "h_namesize" .
.LP
The last record of the archive always contains the name
TRAILER!!!.
Special files, directories, and the trailer are
recorded with
.I "H_filesize"
equal to zero.
.SH SEE ALSO
\fBcpio\fR(1),
\fBfind\fR(1),
\fBstat\fR(2)
.SH HISTORY
A
\fBcpio\fR(1)
command appeared in
AT&T System V UNIX.
This file format is derived from the
AT&T System V UNIX
sources contributed to the public domain by AT&T.
