.TH MOUNT 8 "October 8, 1990"
.SH NAME
mount, umount \- mount and dismount filesystems
.SH SYNOPSIS
.B /usr/etc/mount
[
.B \-p
]
.br
.B /usr/etc/mount
.B \-a 
[ 
.B vd
[
.B f
|
.B n
]]
[ 
.B \-t
.I type 
]
.br
.B /usr/etc/mount
[
.B \-rvd
[
.B f
|
.B n
]]
[
.BI \-t " type"
]
[
.BI \-o " options"
]
.I fsname 
.I dir
.br
.B /usr/etc/mount
[
.B \-vd
[
.B f
|
.B n
]]
[
.BI \-o " options"
]
.IR fsname " | " dir
.LP
.B /usr/etc/umount
[
.BI \-t " type"
]
[
.BI \-h " host"
]
.br
.B /usr/etc/umount
.BR \-a [ v ]
.br
.B /usr/etc/umount
[ 
.B \-v
]
.IR fsname " | " dir
.SH DESCRIPTION
.IX  "mount command"  ""  "\fLmount\fP \(em mount file system"
.IX  "mount file system"  ""  "mount file system \(em \fLmount\fP"
.IX  "file system"  "mount"  ""  "mount \(em \fLmount\fP"
.IX  "umount command"  ""  "\fLumount\fP \(em unmount file system"
.IX  "demount file system"  ""  "demount file system \(em \fLumount\fP"
.IX  "file system"  "unmount"  ""  "unmount \(em \fLumount\fP"
.IX  "file system"  "demount"  ""  "demount \(em \fLumount\fP"
The
.I mount
command
attaches a filesystem
.I fsname
to the file tree at the directory
.IR dir .
The directory
.I dir
may or may not already exist.
If
.I dir
already exists, its contents are hidden until the filesystem
is unmounted, and
.I dir
becomes the name of the newly mounted root.
If
.I fsname
is of the form host:path the filesystem type is assumed to be
.IR nfs .
.LP
The
.I umount
command
detaches the filesystem 
.I fsname
previously mounted on directory
.IR dir .
Either the filesystem name or the mounted-on
directory may be used.
.LP
The
.I mount
and
.I umount
commands
maintain a table of mounted filesystems in
.I /etc/mtab,
described in
.IR mtab (5).
The
.I mount
command
mounts entries onto the filesystem
from data it finds in one of two places.
If NetInfo is running,
it comes from 
.IR netinfo (5). 
Otherwise, the entries are stored in 
.IR /etc/fstab (5).
Note that boot time mounts of type "4.3" filesystems
always occur before NetInfo is running,
and so must be stored in 
.I /etc/fstab
to be seen by the system.
If invoked without an argument,
.I mount
displays the table
from
.IR /etc/mtab .
If invoked with only one of
.I fsname
or
.I dir
mount searches the filesystem table
for an entry whose
.I dir
or
.I fsname
field matches the given argument.
For example, if this line is in \fI/etc/fstab\fR:
.IP
.B "/dev/sd1a /usr 4.3 rw 1 1"
.LP
then the commands
.B "mount /usr"
and
.B "mount /dev/sd1a"
are short for
.B "mount /dev/sd1a /usr"
.LP
.\"Physically write-protected and magnetic tape file systems must
.\"be mounted read-only, or errrors will occur when access times
.\"are updated \(em whether or not any explicit write is
.\"attempted.
.\"More than one remote file system can be mounted on a
.\"directory.  Successive umounts reveal previously mounted file
.\"systems.
.SH "MOUNT OPTIONS"
.TP
.B \-p
Print the list of mounted filesystems in a format suitable for use in 
.I /etc/fstab.
.TP
.B \-a
Attempt to mount all the filesystems described in the filesystem table.
(In this case,
.I fsname
and
.I dir
are taken from the filesystem table.)
If a type is specified all of the filesystems in the filesystem table
with that type are mounted.
Filesystems are not necessarily mounted in the order 
listed in the table.
.TP
.B \-f
Fake a new
.I /etc/mtab
entry, but do not actually mount any filesystems.
.TP
.B \-n
Mount the filesystems without updating
.IR "/etc/mtab" .
(This can be useful for recovering 
from an overly full disk.)
.TP
.B \-v
Verbose \(em
.I mount
displays a message indicating the filesystem being mounted.
.TP
.B \-d
Don't check if NFS mount appears to be mounting a directory on top of itself.
Otherwise, 
.I mount 
ignores such requests.
Since the NFS daemon on a machine
might not have the same filesystem root as the mount process,
this option may be necessary in a chroot'ed environment.
.TP
.B \-t
The next argument is the filesystem type.
The accepted types are
.BR 4.3 ,
.BR nfs ,
.BR dos ,
.BR macintosh ,
and
.B cfs 
(CD-ROM file system).
See
.IR fstab (5)
for a description of these filesystem types.
.TP
.B \-r
Mount the specified filesystem read-only.
This is short for:
.RS
.IP
\fBmount \-o ro\fR \fIfsname dir\fR
.RE
.IP
Physically write-protected and magnetic tape filesystems
must be mounted read-only,
or errors occur when access times are updated
whether or not any explicit write is attempted.
.TP
.B \-o
Specify 
.IR options ,
a list of comma-separated words from the list below.
Some options are valid for all filesystem types,
while others apply to a specific type only.
.sp .5
.IP 
The following is a list of
.I options
valid on 
.I all 
file systems (the default is
.B rw,suid
if the filesystem is mounted by root and
.B rw,nosuid
if the filesystem is not mounted by root):
.RS
.IP \fBrw\fR .75i
read/write.
.IP \fBro\fR
read-only.
.IP \fBsuid\fR
set-uid execution allowed
(cannot be specified; default if root mounts the filesystem).
.IP \fBnosuid\fR
set-uid execution not allowed.
.IP \fBnoauto\fR
do not mount this file system automatically (mount -a).
.IP \fBremount\fR
change the mount options on this file system without unmounting it first.
.RE
.sp .5
.IP
.I options
specific to 
.B nfs
(NFS) file systems.
The defaults are:
.sp .5
.B \0\0\0\0\0fg,mnttimeo=20,retry=1,timeo=7,retrans=3,port=NFS_PORT,hard\fR
.sp .5
The defaults for 
.I rsize 
and 
.I wsize 
set by the kernel.
.RS
.IP \fBbg\fR .75i
if the first mount attempt fails, retry in the background.
.IP \fBfg\fR
retry in foreground.
.IP \fBmnttimeo=\fIn\fR
set mount timeout to
.I n
seconds.
.IP \fBretry=\fIn\fR
set number times to retry mount to
.I n.
.IP \fBrsize=\fIn\fR
set read buffer size to 
.I n 
bytes.
.IP \fBwsize=\fIn\fR
set write buffer size to 
.I n
bytes.
.IP \fBtimeo=\fIn\fR
set NFS timeout to 
.I n 
tenths of a second.
.IP \fBretrans=\fIn\fR
set number of NFS retransmissions to 
.I n.
.IP \fBport=\fIn\fR
set server IP port number to 
.I n.
.IP \fBsoft\fR
return error if server doesn't respond. Do 
.I not
use this option with the
.B rw 
option.
.IP \fBhard\fR
retry request until server responds.
.IP \fBintr\fR
allow keyboard interrupts on hard mounts.
.IP \fBnet\fR
Tell the NFS automounter to recognize this as a "network" mount.
The mount command will ignore these entries
and allow the autonfsmount(8) to take care of them.
This option allows one to create a uniform
view of the network from all machines.
Typically, the mount point specified is "/Net".
A mount of the form "mount -o net MACHINE:PATH /Net"
translates to "mount MACHINE:PATH /Net/MACHINE/PATH".
If the mount is performed on the machine serving the file system,
then no actual mount occurs.
Instead, a symbolic link is created from "/Net/MACHINE" to "/".
.IP \fBacregmin=\fIn\fR
set minimum time interval (in seconds) for file entry caching
.IP \fBacregmax=\fIn\fR
set maximum time interval (in seconds) for file entry caching
.IP \fBacdirmin=\fIn\fR
set minimum time interval for directory entry caching
.IP \fBacdirmax=\fIn\fR
set maximum time interval for directory entry caching
.IP \fBnoac\fR
set no file attribute caching
.RE
.IP
The
.B bg
option causes 
.I mount
to run in the background if the server's
.IR mountd (8)
does not respond. 
.I mount 
attempts each request
.BI retry= n
times before giving up.
Once the filesystem is mounted,
each 
NFS 
request made in the kernel waits
.BI timeo= n
tenths of a second for a response.
If no response arrives, the time-out is multiplied by 
.B 2 
and the request is retransmitted.
When
.BI retrans= n
retransmissions have been sent with no reply a
.B soft
mounted filesystem returns an error on the request and a
.B hard
mounted filesystem prints a message and retries the request.
Filesystems that are mounted 
.B rw
(read-write)
should use the 
.B hard
option.
The
.BI intr
option allows keyboard interrupts to kill a process that is hung
waiting for a response on a hard mounted filesystem.
The number of bytes in a read or write request can be set with the
.B rsize
and
.B wsize
options.
.LP
The attribute caching options
can be used
to defeat or modify
client-side caching of attributes
relating to objects
accessed via NFS from a server.
Changing these options
can have a severe impact
on the client-side performance
of an NFS filesystem.
A typical scenario
where changing the parameters is beneficial
is a multi-workstation development environment,
where multiple clients
are performing read/write file access
to a common source file set.
.SH "UMOUNT OPTIONS"
.TP
.BI \-h " host"
Unmount all filesystems listed in
.I /etc/mtab
that are remote-mounted from 
.I host.
.TP
.B \-a
Attempt to unmount all the filesystems currently mounted (listed
in
.IR /etc/mtab ).
In this case,
.I fsname
is taken from
.I /etc/mtab.
.TP
.B \-v
Verbose \(em
.I umount
displays a message indicating the filesystem being unmounted.
.SH EXAMPLES
.nf
.ta \w'mount \-o hard server:/usr/src /usr/src 'u
mount /dev/sd1a /usr            	mount a local disk
mount \-ft 4.3 /dev/nd0 /       	fake an entry for nd root
mount \-at 4.3                  	mount all 4.3 filesystems
mount \-t nfs serv:/usr/src /usr/src	mount remote filesystem
mount serv:/usr/src /usr/src    	same as above
mount \-o hard serv:/usr/src /usr/src	same as above but hard mount
mount \-p > /etc/fstab          	save current mount state
.fi
.SH FILES
.DT
/etc/mtab	table of mounted filesystems
.br
/etc/fstab	table of filesystems mounted at boot
.IX "files used by programs" "\fL/etc/mtab\fR \(em table of mounted filesystems"
.IX "files used by programs" "\fL/etc/fstab\fR \(em table of filesystems to mount at boot"
.SH "SEE ALSO"
mount(2), unmount(2), fstab(5), mountd(8C), nfsd(8C), netinfo(5)
.SH BUGS
Mounting filesystems full of garbage crashes the system.
.LP
If the directory on which a filesystem is to be mounted is a
symbolic link, the filesystem is mounted on 
.I "the directory to which the symbolic link refers,"
rather than being mounted on top of the symbolic link itself. 
