.TH SUM32 8 "August 26, 1994" "NeXT Computer, Inc."
.SH NAME
sum32 \- checksum file contents
.SH SYNOPSIS
\fBsum32\fR \fIfile\fR ...
.SH DESCRIPTION
\fISum32\fR calculates and prints a 32-bit checksum for the named file(s). This checksum is calculated in the same way as the checksums recorded in BOM ("Bill of Materials") files.
.SH "SEE ALSO"
bom(5), lsbom(8)
