.\" @(#)yppoll.8	1.2 87/08/23 3.2/4.3NFSSRC
.\" @(#)yppoll.8	1.2 87/02/10 NFSSRC
.\" @(#)yppoll.8 1.1 86/09/25 SMI; 
.TH YPPOLL 8 "4 June 1986"
.SH NAME
yppoll - what version of a YP map is at a YP server host
.SH SYNOPSIS
.B /usr/etc/yp/yppoll
[ \fB-h \fIhost\fR ]
[ \fB-d \fIdomain\fR ]
.I mapname
.SH DESCRIPTION
.IX yppoll "" "\fLyppoll\fR \(em yellow pages version inquiry"
.I yppoll 
asks a 
.I ypserv 
process what the order number is, and which host
is the master YP server for the named map.  
If the server is a
v.1 YP protocol server, 
.I yppoll
uses the older protocol to communciate with 
it.  In this case, it also uses the older diagnostic messages in
case of failure.
.SH OPTIONS
.IP "\fB\-h \fIhost\fR"
Ask the 
.I ypserv 
process at
.I host
about the map parameters.  If 
.I host 
isn't specified, the YP server for the local host is used.
That is, the default host is the one returned by
.IR ypwhich (8).
.IP "\fB\-d \fIdomain\fR"
Use
.I domain
instead of the default domain.
.SH "SEE ALSO"
ypserv(8), ypfiles(5)
