.TH "GAMES" 6 "October 2, 1990" "NeXT Computer, Inc."
.SH NAME
games \- UNIX games
.SH DESCRIPTION
The UNIX terminal-based games
and their manual pages
are not included in the NEXTSTEP release.
In lieu of these,
the \fB/NextDeveloper/Demos\fR directory
contains a number of NEXTSTEP applications that you might want to try.
.SH NEXTSTEP DEMO PROGRAMS
The demos in \fB/NextDeveloper/Demos\fR
are designed to give aspiring programmers
a taste of what's possible with NEXTSTEP.
If you're interested in science,
music, art, signal processing,
games, animation, timing, optics, PostScript, chaos, electronics, chess,
and so on,
you should find something compelling in this collection of demos.    
.PP
Note that these demo programs
are not generally maintained,
and usually do not come with sources,
although the source code for some demos
is available in the directory \fB/NextDeveloper/Examples\fR.
