.\" @(#)group.5	1.2 87/08/23 3.2/4.3NFSSRC
.\" @(#)group.5	1.2 87/02/16 NFSSRC
.\" @(#)group.5 1.1 85/12/28 SMI; from UCB 4.2
.TH GROUP 5 "1 February 1985"
.SH NAME
group \- group file
.SH SYNOPSIS
.B /etc/group
.SH DESCRIPTION
.\" .IX  "group file"  ""  "\fLgroup\fP \(em group file format"
NOTE: This file is superceded by 
.I netinfo(5)
if NetInfo is running.
.PP
.I Group
contains for each group the following information:
.IP \(bu 2
group name
.IP \(bu 2
encrypted password
.IP \(bu 2
numerical group ID
.IP \(bu 2
a comma separated list of all users allowed in the group
.LP
This is an
.SM ASCII
file.  The fields are separated by colons;
each group is separated from the next by a new-line.
If the password field is null, no password is demanded.
.LP
This file resides in the
.I /etc
directory.  Because of the encrypted passwords,
it can and does have general read permission and can be
used, for example, to map numerical group ID's to names.
.PP
A group file can have a line beginning with a plus (+),
which means to incorporate entries from the yellow pages.
There are two styles of + entries:
All by itself, + means to insert the entire contents
of the yellow pages group file at that point;
.I +name
means to insert the entry (if any) for
.I name
from the yellow pages at that point.
If a + entry has a non-null password or group member field,
the contents of that field will overide
what is contained in the yellow pages.
The numerical group ID field cannot be overridden.
.PP
A group file can also have a line beginning
with a minus (-),
these entries are used to disallow group entries.
There is only one style of - entries:
An entry that consists of
.I -name
means to disallow any subsequent entry (if any) for
.IR name .
These entries will be disallowed
regardless of whether the subsequent entry comes
from the yellow pages or the local group file.
.SH EXAMPLE
.PP
.ft L
.nf
-oldproj
+myproject:::bill, steve
+:
.fi
.PP
If these entries appear at the end of a group file, then the group 
.I oldproj
 will be ignored if it appears after the entry
.IR "-oldproj" .
Also, the group
.I myproject
will have members
.IR bill and steve ,
and the password and group ID of the yellow pages entry for the group
.IR myproject .
All the groups listed in the yellow pages
will be pulled in and placed after the entry for
.IR myproject .
.SH FILES
/etc/group - if NetInfo is not running
/etc/yp/group
.SH "SEE ALSO"
setgroups(2), initgroups(3), crypt(3), passwd(1), passwd(5), netinfo(5)
.SH BUGS
The
.IR passwd (1)
command won't change group passwords.
