.\" @(#)mntent.5	1.2 92/05/06 3.2/4.3NFSSRC; JJ
.\" @(#)mntent.5	1.2 87/08/23 3.2/4.3NFSSRC
.\" @(#)mntent.5	1.2 87/02/10 NFSSRC
.\" @(#)mntent.5 1.1 86/09/25 SMI;
.TH MNTENT 5 "May 19, 1986"
.SH NAME
mntent, fstab \- static information about filesystems
.SH SYNOPSIS
.B #include <mntent.h>
.SH DESCRIPTION
.IX  "mntent file"  ""  "\fLmntent\fP \(em file system static information"
.IX  "file system"  "mntent file"  ""  "\fLmntent\fP \(em static information"
.IX  "static file system information mntent"  ""  "static file system information \(em \fLmntent\fP"
NOTE:  Unless NetInfo is disabled, 
.I /etc/fstab 
is accessed only at boot time,
when it's used to mount all file systems of type 4.3.  
.PP
The file
.I /etc/fstab
describes the file systems and swapping partitions used by the local machine.
It is created by the system administrator using a text editor,
and processed by commands which mount, unmount, check consistency of,
dump and restore file systems,
and by the system in providing swap space.
.LP
It consists of a number of lines of the form:
.IP
fsname dir type opts freq passno
.LP
an example of which would be:
.IP
/dev/xy0a / 4.3 rw,noquota 1 2
.LP
The entries in this file are accessed using the routines in
.IR getmntent (3),
which returns a structure of the following form:
.IP
.ta \w'#define'u +\w'char\0\0'u +\w'*mnt_fsname;\0\0'u
.nf
struct mntent {
	char	*mnt_fsname;	/* file system name */
	char	*mnt_dir;	/* file system path prefix */
	char	*mnt_type;	/* 4.3, nfs, dos, macintosh, cfs, or ignore */
	char	*mnt_opts;	/* ro, etc. */
	int	mnt_freq;	/* dump frequency, in days */
	int	mnt_passno;	/* pass number on parallel fsck */
};
.fi
.LP
There is one entry per line in the file, and
the fields are separated by white space.
A ``#'' as the first non-white character indicates a comment.
.LP
The
.I mnt_opts
field consists of a string of comma separated options.
Some of the
options are common to all filesystem types,
and others only make sense
for a single filesystem type.
It is important to specify
that a removable filesystem
(such as floppy disk)
is
.B removable,
or
.B ro
if a filesystem is read-only.
See 
.IR mount (8)
for a more complete description of the options available.
.LP
The \fImnt_type\fP field determines how the 
.I mnt_fsname,
and 
.I mnt_opts
fields will be interpreted.
Below is a list of the file system types currently supported and
the way each of them interprets these fields.
See /NextDeveloper/Headers/bsd/mntent.h
for additional,
though unsupported,
file system types.
.LP
.B 4.3
.RS
.IP mnt_fsname 12
Must be a block special device.
.IP mnt_opts 12
Valid opts are: ro, rw, suid, nosuid.
.RE
.LP
.B nfs
.RS
.IP mnt_fsname 12
servername:volumename to be mounted
.IP mnt_opts 12
Valid opts are: ro, rw, nosuid, hard, soft, bg, fg, retry, rsize, wsize,
timeo, retrans, port, intr, net, secure, grpid, nosub, multi, acregmin, acregmax, noac, acdirmin, acdirmax.
.RE
.LP
.B dos
.RS
.IP mnt_fsname 12
Must be a raw device.
.IP mnt_opts 12
Ignored.
.PP
NOTE:  This file system does not support SCSI hard disks, 
CD-ROMs, 
or 2.88 MB floppies;
it supports only 720KB and 1.4 MB floppies.
To mount a dos volume, the appropriate loadable kernel server
must already be loaded into the system.
.RE
.LP
.B macintosh
.RS
.IP mnt_fsname 12
Must be a raw device.
.IP mnt_opts 12
Ignored.
.PP
NOTE:  To mount a macintosh volume, the appropriate loadable kernel server
must already be loaded into the system.
.RE
.LP
.B cfs
(CD-ROM file system)
.RS
.IP mnt_fsname 12
Must be a raw device.
.IP mnt_opts 12
Ignored.
.PP
NOTE:  To mount a cfs volume, the appropriate loadable kernel server
must already be loaded into the system.
.RE
.\"
.\".LP
.\".B 4.2
.\".RS
.\".IP mnt_fsname 12
.\"Must be a block special device.
.\".IP mnt_opts 12
.\"Valid opts are: ro, rw, suid, nosuid.
.\".RE
.\"
.\".LP
.\".B SWAP
.\".RS
.\".IP mnt_fsname 12
.\"Must be a block special device swap partition.
.\".IP mnt_opts 12
.\"Ignored.
.\".RE
.LP
If the
.I mnt_type
is specified as ``ignore'' the entry is ignored.
This is useful to show disk partitions which are currently not used.
Disks that are specified as as ``ignore'' are also not automounted by the Workspace in NEXTSTEP.  This is useful when your disk has data in a format that NEXTSTEP doesn't recognize, and you want it to ignore the disk.
.LP
The field \fImnt_freq\fP indicates how often each partition should
be dumped by the
.IR dump (8)
command (and triggers that command's \fBw\fP option which tells
which file systems should be dumped).
Most systems set the \fImnt_freq\fP field to 1,
indicating that the
file systems are dumped each day.
.LP
The final field \fImnt_passno\fP is used by the disk consistency
check program
.IR fsck (8)
to allow overlapped checking of file systems during a reboot.
All
file systems with \fImnt_passno\fP of 1 are first checked simultaneously,
then all file systems with \fImnt_passno\fP of 2, and so on.
It is usual to make the \fImnt_passno\fP of the root file system have
the value 1,
and then check one file system on each available disk
drive in each subsequent pass to the exhaustion of file system partitions.
.LP
.I /etc/fstab
is only
.I read
by programs, and not written;
it is the duty of the system administrator to properly create 
and maintain this file.
The order of records in
.I /etc/fstab
is important because
.I fsck,
.I mount,
and
.I umount
process the file sequentially; file systems must appear
\fIafter\fP file systems they are mounted within.
.SH FILES
/etc/fstab
.IX "files used by programs" "\fL/etc/fstab\fR \(em table of filesystems to mount at boot"
.SH SEE ALSO
fsck(8), getmntent(3), mount(8), quotacheck(8), quotaon(8), umount(8)
