.\" @(#)netgroup.5	1.2 87/08/23 3.2/4.3NFSSRC
.\" @(#)netgroup.5	1.2 86/12/31 NFSSRC
.\" @(#)netgroup.5 1.1 86/09/25 SMI;
.TH NETGROUP 5 "1 February 1985"
.SH NAME
netgroup \- list of network groups
.SH DESCRIPTION
NOTE: This manual page is only relevant if one is running Yellow Pages.
See netinfo(5) for information on using netgroups with NetInfo.
.PP
.IX  "netgroup file"  ""  "\fLnetgroup\fP \(em network groups list"
.I Netgroup
defines network wide groups,
used for permission checking when doing
remote mounts, remote logins, and remote shells.
For remote mounts, the information in 
.I netgroup
is used to classify machines;
for remote logins and remote shells,
it is used to classify users.
Each line of the
.I netgroup
file defines a group and has the format
.IP
 groupname member1 member2 ....
.PP
where member\fIi\fP\| is either another group name, or a triple:
.IP
 (hostname, username, domainname)
.PP
Any of three fields can be empty,
in which case it signifies a wild card.
Thus
.IP
 universal (,,)
.PP
defines a group to which everyone belongs.
Field names that begin with something other than a letter, digit or underscore
(such as ``-'') work in precisely the opposite fashion. 
For example, consider the following entries:
.IP
 justmachines	(analytica,-,sun)
 justpeople	(-,babbage,sun)
.PP
The machine
.I analytica
belongs to the group
.I justmachines
in the domain
.IR sun ,
but no users belong to it.
Similarly, the user
.I babbage
belongs to the group 
.I justpeople
in the domain
.IR sun ,
but no machines belong to it. 
.PP
Network groups are contained in the yellow pages,
and are accessed through these files:
.IP
 /etc/yp/\fIdomainname\fP/netgroup.dir
 /etc/yp/\fIdomainname\fP/netgroup.pag
 /etc/yp/\fIdomainname\fP/netgroup.byuser.dir
 /etc/yp/\fIdomainname\fP/netgroup.byuser.pag
 /etc/yp/\fIdomainname\fP/netgroup.byhost.dir
 /etc/yp/\fIdomainname\fP/netgroup.byhost.pag
.PP
These files can be created from
.I /etc/netgroup
using
.IR makedbm (8).
.SH FILES
/etc/netgroup
.br
/etc/yp/\fIdomainname\fP/netgroup.dir
.br
/etc/yp/\fIdomainname\fP/netgroup.pag
.br
/etc/yp/\fIdomainname\fP/netgroup.byuser.dir
.br
/etc/yp/\fIdomainname\fP/netgroup.byuser.pag
.br
/etc/yp/\fIdomainname\fP/netgroup.byhost.dir
.br
/etc/yp/\fIdomainname\fP/netgroup.byhost.pag
.IX "files used by programs" "\fL/etc/netgroup\fR \(em network groups"
.IX  "trusted hosts list"  ""  "trusted hosts list \(em \fLhosts.equiv\fP"
.IX "files used by programs" "\fL/etc/hosts.equiv\fR \(em list of trusted clients"
.IX "files used by programs" "\fL/etc/yp/\fIdomain\fL/netgroup*\fR \(em list of network groups for YP domain"
.SH "SEE ALSO"
getnetgrent(3), exportfs(8), makedbm(8), ypserv(8), netinfo(5)
