.\"	@(#)assert.3	6.2 (Berkeley) 5/12/86
.\"
.TH ASSERT 3 "August 1, 1992"
.AT 3
.SH NAME
assert \- program verification
.SH SYNOPSIS
.B #include <assert.h>
.PP
.B void assert(int \fIexpression\fP);
.SH DESCRIPTION
.PP
.I Assert
is a macro that indicates
.I expression
is expected to be true at this point in the program.
It causes an
.IR abort (3)
with a diagnostic comment on
.B stderr
when
.I expression
is false (0).
Compiling with the 
.IR cc (1)
option
.SM
.B \-DNDEBUG
effectively deletes
.I assert
from the program.
.SH DIAGNOSTICS
`Assertion failed: file
.I f
line
.I n.'
.I F
is the source file and
.I n
the source line number of the
.I assert
statement.
