.TH GETSEGBYNAME 3  "March 1, 1989" "NeXT Computer, Inc."
.SH NAME
getsegbyname \- get the segment command for the named segment
.SH SYNOPSIS
.nf
\fB#include <ldsyms.h>\fR
\fB#include <sys/loader.h>\fR
.PP
const struct segment_command *\fBgetsegbyname\fR(char *\fIsegname\fR);
.fi
.SH DESCRIPTION
This routine returns the segment_command structure for the named segment if it
exists in the Mach-O (Mach object) executable
.IR getsegbyname (3)
is linked into.  Otherwise
.IR getsegbyname (3)
returns NULL.  It uses the link editor defined symbol _mh_execute_header and
just looks through the load commands.  Since these are mapped into the text
segment they are read-only and thus
.I const.
.SH "SEE ALSO"
end(3), getsectbyname(3), getmachheaders(3)
