.TH THREADS 3 "January 17, 1989" "NeXT Computer, Inc."
.CM 4
.SH NAME
C-Threads \- support for concurrent programming in C under MACH
.SH "DESCRIPTION"
The
.I "C Threads"
runtime library provides concurrent threads of control, shared variables,
mutual exclusion, and synchronization via condition variables.
.PP
For documentation,
see the
\fINeXT Developer's Library\fR
(accessible through the NeXT Developer target of the Digital Librarian).
