.\" Copyright (c) 1980 Regents of the University of California.
.\" All rights reserved.  The Berkeley software License Agreement
.\" specifies the terms and conditions for redistribution.
.\"
.\"	@(#)hier.7	6.1 (Berkeley) 5/20/85
.\"
.TH HIER 7 "April 1, 1989"
.UC 4
.SH NAME
hier \- file system hierarchy
.SH DESCRIPTION
The standard hier(7) man page provides a representative UNIX
directory hierarchy, which is very different from the NeXT directory hierarchy and therefore not included here.
For a description of the NeXT directory hierarchy, see
the \fINeXT Operating System Software\fR manual in the  \fINeXT Developer's Library\fR).
.SH SEE ALSO
ls(1),
apropos(1),
whatis(1),
whereis(1),
finger(1),
which(1),
ncheck(8),
find(1),
grep(1)
