/*
 * Copyright (c) 1993 NeXT Computer, Inc.
 *
 * HPPA Family:	Machine dependent exception codes.
 *
 * HISTORY
 *
 * 2 July 1993 Mac Gillon at NeXT
 *	Created.
 */
 
#ifndef	_MACH_HPPA_EXCEPTION_H_
#define	_MACH_HPPA_EXCEPTION_H_

/*
 *	EXC_BAD_INSTRUCTION
 */

#define EXC_HPPA_PRIVILEGED_INSTRUCTION	1
#define EXC_HPPA_PRIVILEGED_REGISTER	2
#define EXC_HPPA_RESERVED_OPERATION	4

/*
 *	EXC_BAD_ACCESS
 */
#define EXC_HPPA_SEGMENTATION_VIOLATION	16
#define EXC_HPPA_PROTECTION_VIOLATION	17
#define EXC_HPPA_UNALIGNED_FAILED	18
#define EXC_HPPA_UNALIGNED_SUCCEEDED	19

/*
 *	EXC_ARITHMETIC
 */

#define EXC_HPPA_OVERFLOW		1
#define EXC_HPPA_CONDITION		2
#define EXC_HPPA_ASSIST_FAILED		3
#define EXC_HPPA_ASSIST_SUCCEEDED	4
#define EXC_HPPA_EMULATION_FAILED	5
#define EXC_HPPA_EMULATION_SUCCEEDED	6

/*
 *	EXC_BREAKPOINT
 */

#define EXC_HPPA_BREAKPOINT		1
#define EXC_HPPA_TAKENBRANCH		2
#define EXC_HPPA_DEBUG			3

#define EXC_UNIX_BAD_SYSCALL		0x10000

#endif	_MACH_HPPA_EXCEPTION_H_
