.TH "MachFunctions" 2 "April 18, 1990" "NeXT Computer, Inc."
.SH NAME
MachFunctions \- Mach Functions
.SH DESCRIPTION
Mach functions are not documented in the UNIX manual pages.
For information about the Mach functions, see the
\fINeXT Developer's Library\fR
(accessible on-line through the Digital Librarian).
