.\" @(#)domainname.1	1.1 87/07/28 3.2/4.3 NFSSRC
.TH DOMAINNAME 1 "23 September 1985"
.SH NAME
domainname \- set or display name of current domain system
.SH SYNOPSIS
.B domainname
[ \fInameofdomain\fR ]
.SH DESCRIPTION
.IX "domainname command"  ""  "\fLdomainname\fP \(em set/display domain name"
.IX "current domain, set or display name \(em \fLdomainname\fR"
.IX display  "current domain name \(em \fLdomainname\fR"
.IX set  "current domain name \(em \fLdomainname\fR"
Without an argument,
.I domainname
displays the name of the current domain.
Only the super-user can set the domainname by giving an argument;
this is usually done in the startup script
.IR /etc/rc.local .
Currently, domains are only used by the yellow pages, to refer
collectively to a group of hosts.
.SH SEE ALSO
ypinit(8)
