.\" Copyright (c) 1992 NeXT Computer, Inc.
.\" All rights reserved.
.\"
.\"	@(#)ixbuild.1	3.0 (NeXT) 07/14/92
.\"
.TH IXBUILD 1 "July 14, 1992" "NeXT Computer, Inc."
.SH NAME
ixBuild, ixClean, ixDump, ixFind, ixRemove, ixStat, pword \- NEXTSTEP Release 2 indexing utilities
.SH DESCRIPTION
The 
.B ixBuild 
and 
.B ixClean 
commands have been replaced in Release 3 by the 
.B ixbuild 
command.  
The 
.B ixFind 
command is replaced by 
.BR ixsearch .  
The other utilities listed above
are either replaced by 
.BR ixbuild ,
not needed, or not available in NEXTSTEP Release 3.

.SH SEE ALSO
ixbuild(1), ixsearch(1), ixdomain(1),
Indexing Kit Documentation in \fINEXTSTEP General Reference\fR

