.TH  MIG 1 "January 17, 1989" "NeXT Computer, Inc."
.CM 4
.SH NAME
mig \- Mach message interface generator
.SH SYNOPSIS
.B mig [-qQvVrRtT]
\fIdefinitions-file\fR

.SH DESCRIPTION
.I MiG
uses the interface definitions in the \fIdefinitions-file\fR and creates
two C modules: \fIsubsystem\fR\fBUser.c\fR and
\fIsubsystem\fR\fBServer.c\fR.  These modules implement the user and the
server ends of a remote procedure call interface to the subsystem.  A
header file \fIsubsystem\fR\fB.h\fR is also generated that defines the external
functions and can be included in any code using the user interface.

The switches are:
.TP
.I -r,-R
If \fI-r\fR, use msg_rcp().  If \fI-R\fR, use msg_send()/msg_receive() pairs.
The default is
\fI-r\fR.
.TP
.I -t,-T
If \fI-t\fR, generate code for multi-threaded applications (not implemented yet).
If \fI-T\fR, generate code for single thread application.  The default is
\fI-T\fR.
.TP
.I -q,-Q
If \fI-q\fR, warning statements will be suppressed.  If \fI-Q\fR, warning statements
are printed.  The default is
\fI-Q\fR.
.TP
.I -v,-V
If \fI-v\fR, all the types, routines and arguments are printed out as
the are encountered.  If \fI-V\fR, the compilation is silent.  The
default is
\fI-V\fR.
.i0
.DT
.PP
For additional documentation, see the chapter "The Mach Operating System"
in the \fINEXTSTEP Operating System Software\fR manual
(this manual can be viewed on-line using the NeXT Digital Librarian).

.SH FILES
\fIsubsystem\fR.h \- the include file for the user routines
.br
\fIsubsystem\fRUser.c \- the code for the user side of the interface
.br
\fIsubsystem\fRServer.c \- the code for the server side of the interface
.br
/NextDeveloper/Headers/mach/mig_errors.h \- error codes generated by mig code
