.TH "NeXT Applications" 1 "October 10, 1990" "NeXT Computer, Inc."
.SH NAME
NeXTApps \- NeXT applications
.SH DESCRIPTION
NeXT applications are not documented in the UNIX manual pages.
See the
.I NeXT User's Guide
for information about NeXT user applications.
.PP
For information about NeXT developer applications, see the
.I NeXT Developer's Library
or search in the NeXT
Developer bookshelf in the Digital Librarian.
